name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: kainos-jobs-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: postgresql://${{ secrets.DB_TEST_USER }}:${{ secrets.DB_TEST_PASS }}@${{ secrets.DB_TEST_HOST }}:${{ secrets.DB_TEST_PORT }}/${{ secrets.DB_TEST_DBNAME }}
    
    - name: Check Prisma Client
      run: ls -l ../generated/prisma/client

    
    - name: Run linting
      run: npm run check


    - name: Create .env.test
      run: |
        cat > .env.test << EOF
        PORT=${{ secrets.TEST_PORT }}
        DB_USER=${{ secrets.DB_TEST_USER }}
        DB_PASSWORD=${{ secrets.DB_TEST_PASS }}
        DB_HOST=${{ secrets.DB_TEST_HOST }}
        DB_PORT=${{ secrets.DB_TEST_PORT }}
        DB_NAME=${{ secrets.DB_TEST_DBNAME }}
        DB_SCHEMA=${{ secrets.DB_TEST_SCHEMA }}
        EOF

    - name: Run Prisma migrations
      run: npx dotenv -e .env.test -- prisma migrate deploy

    - name: Run tests
      run: npm run test:coverage